spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-api
          uri: lb://product-api
          predicates:
            - Path=/api/v1/product

        - id: order-api
          uri: lb://order-api
          predicates:
            - Path=/api/v1/order

        - id: inventory-api
          uri: lb://inventory-api
          predicates:
            - Path=/api/v1/inventory

        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka
          filters:
            - SetPath=/

        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080

logging:
  level:
    root: info
    org.springframework.cloud.gateway: trace
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: info
