spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none # create-drop # update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5111/retaildb
    username: mahmoudmutawe
    password: pass
server:
  port: 8082