-- retaildb=# CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- CREATE EXTENSION
-- retaildb=# SELECT uuid_generate_v1();
--            uuid_generate_v1
-- --------------------------------------
--  32542bce-0ebd-11ee-8278-367dda2b2c40
-- (1 row)
--
-- retaildb=# SELECT uuid_generate_v4();
--            uuid_generate_v4
-- --------------------------------------
--  b8cb86ab-2148-45f2-b5d6-292159eb9cf0
-- (1 row)

-- retaildb=# CREATE TABLE orders (
-- retaildb(# order_number uuid DEFAULT uuid_generate_v4 ());
-- CREATE TABLE
-- retaildb=# CREATE TABLE items (
-- retaildb(# item_id SERIAL PRIMARY KEY,
-- retaildb(# sku_code VARCHAR(255),
-- retaildb(# quantity INT,
-- retaildb(# price NUMERIC(5,2));
-- CREATE TABLE
-- retaildb=#
-- retaildb=#
-- retaildb=# CREATE TABLE order_item (
-- retaildb(# item_id INTEGER REFERENCES items(item_id),
-- retaildb(# order_number uuid REFERENCES orders(order_number),
-- retaildb(# CONSTRAINT courses_students_pk PRIMARY KEY(course_id,student_id) );
-- ERROR:  column "course_id" named in key does not exist
-- LINE 4: CONSTRAINT courses_students_pk PRIMARY KEY(course_id,student...
--         ^
-- retaildb=#
-- retaildb=#
-- retaildb=# CREATE TABLE order_item (
-- retaildb(# item_id INTEGER REFERENCES items(item_id),
-- retaildb(# order_number uuid REFERENCES orders(order_number),
-- retaildb(# CONSTRAINT orders_items_pk PRIMARY KEY(order_number,item_id) );
-- ERROR:  there is no unique constraint matching given keys for referenced table "orders"
-- retaildb=# ALTER TABLE orders ADD PRIMARY KEY (order_number);
-- ALTER TABLE
-- retaildb=#
-- retaildb=# CREATE TABLE order_item (
-- retaildb(# item_id INTEGER REFERENCES items(item_id),
-- retaildb(# order_number uuid REFERENCES orders(order_number),
-- retaildb(# CONSTRAINT orders_items_pk PRIMARY KEY(order_number,item_id) );
-- CREATE TABLE