server:
  port: 8761 # default eureka port

eureka:
  instance.hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  api-access:
    username: ${EUREKA_USERNAME:eureka}
    password: ${EUREKA_password:eureka}