spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5111/retaildb
    username: mahmoudmutawe
    password: pass
    driverClassName: org.postgresql.Driver
server:
  port: 8081