spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none # create-drop # update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5111/retaildb
    username: mahmoudmutawe
    password: pass
  application:
    name: product-api
server:
  port: 0
#  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka@localhost:8761/eureka