spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none # create-drop # update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5111/retaildb
    username: mahmoudmutawe
    password: pass
  application:
    name: inventory-api

server:
  port: 0
#  port: 8083
#server.port=${inventory.server.port}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#  instance:
#    non-secure-port-enabled: true
#    secure-port-enabled: false
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    non-secure-port: ${inventory.server.port}


